spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    # locations: "classpath:db/migration"
  jpa:
    show-sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        format_sql: true
flyway:
  enabled: true
  validate-on-migrate: true

# spring.jpa.hibernate.ddl-auto = create

 