create table produto (
  id bigint generated by default as identity,
  categoria varchar(255),
  cod_barras varchar(255),
  nome varchar(255),
  primary key (id)
);

create table supermercado (
  id bigint generated by default as identity,
  endereco varchar(255),
  fone varchar(255),
  nome varchar(255),
  primary key (id)
);

create table supermercado_produto (
  id bigint generated by default as identity,
  preco float(53),
  produto_id bigint,
  supermercado_id bigint,
  primary key (id)
);

alter table
  if exists supermercado_produto
add
  constraint UniqueSupermercadoAndProduto unique (supermercado_id, produto_id);

alter table
  if exists supermercado_produto
add
  constraint FKpqqd7c6wnxt4nrr1ruy4jm3wb foreign key (produto_id) references produto;

alter table
  if exists supermercado_produto
add
  constraint FK6f2oi15k4lr9f1asurfrswp3p foreign key (supermercado_id) references supermercado;